config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :restaurants
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :restaurants
  root 'welcome#homepage'

  get '/welcome', to: 'welcome#homepage'
  get '/welcome/choice', to: 'welcome#select_choices'
  get '/welcome/trending', to: 'welcome#trending'
  get '/welcome/about', to: 'welcome#about'
  get '/date_plan', to: 'date_plan#plan'
  post '/date_plan', to: 'date_plan#create'
  get '/date_plan/:id', to: 'date_plan#show', as: 'show_date_plan'
  delete '/date_plan/:id', to: 'date_plan#destroy'
  get '/user', to: 'user#show'

end

app/models/date_plan.rb
class DatePlan < ApplicationRecord
  belongs_to :event
  belongs_to :restaurant
  belongs_to :user

end

app/controllers/date_plan_controller.rb
require 'date'

class DatePlanController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @date_plan = DatePlan.new
  end

  def show
    load_user
    @date_plan = @user.date_plans.find(params[:id])
  end


  def create
    @date_plan = DatePlan.new
    @date_plan.restaurant_id = params["restaurant"]
    @date_plan.user_id = current_user.id
    @date_plan.date = Date.strptime(params['date'], '%m/%d/%Y')
    @date_plan.event_id = params["event"]

    if @date_plan.save
      flash[:success] = "We have sent you an email confirmation to current_user.email"
      redirect_to show_date_plan_url(@date_plan)
    else
      flash[:notice] = "You have to select a restaurant to save your date plan!"
      redirect_back fallback_location: @post
    end
  end

  def destroy
    @date_plan = DatePlan.find(params[:id])
    @date_plan.destroy
    redirect_to user_path
  end


  def plan
    @new_list = []
    @date = Date.strptime(params['date'], '%m/%d/%Y')
    @quantity = params['quantity'].to_i
    @price_max = params['price_max'].to_i
    @price_max_for_quantity = @quantity * @price_max
    @restaurant_list = Restaurant.joins(:categories).where("categories.category" => params["category"].keys)
    @category = params["category"].keys
    @event_list = Event.where("category in (?)", event_filter_categories)
    @event_categories = event_filter_categories


    list_of_restaurants_matching_days_open(@restaurant_list)
    real_price(@restaurant_list)

    event_list_price(@event_list, @restaurant_list)
    @new_list = @new_list.sample(3)

    respond_to do |format|
     format.html
     format.json { render json: @new_list }
   end

  end

  private

  def event_filter_categories
    categories = params[:event_category].select do |key, value|
      value == "1"
    end
    return categories.keys
  end

  def list_of_restaurants_matching_days_open(restaurant_list)
    restaurant_list = restaurant_list.all.select do |restaurant|
       days_open = restaurant.restaurant_hours.map {|h| Date::DAYNAMES[h.day - 6]}
       list_days_open = days_open.select do |day|
         day == @date.strftime('%A')
       end
       list_days_open.length > 0
    end
  end

  def real_price(list)
    list.each do |restaurant|
      if restaurant.price == '$'
        restaurant.price = 15
      elsif restaurant.price == '$$'
        restaurant.price = 30
      end
    end
  end

  def event_list_price(event_list, restaurant_list)
    event_list.each do |event|
      restaurant_list.each do |restaurant|
        if event.price.to_i + restaurant.price.to_i <= @price_max
         @new_list.push([event, restaurant])
        end
      end
    end
  end

  def load_user
    @user = User.find_by(id: current_user.id)
  end


end

app/views/date_plan/plan.html.erb
<h1 class="food"><span>FOOD & EVENT</span></h1>

<h4> Your chosen categories</h4>
<div class="food-category">
  <h5>Food:</h5>
  <% @category.each do |cat|%>
    <span><%= cat %></span>
    <% end %>
</div>

<div class="event-category">
  <h5>Event:</h5>
  <% @event_categories.each do |category| %>
  <span><%= category.capitalize %></span>
  <% end %>
</div>

<p>
  for <%= @date.strftime('%A, %b %e %Y' ) %> </br>
</p>

<section class="plan-container">
<%= form_tag "/date_plan", method: :post do %>
  <% @new_list.each do |array| %>
    <td>
      <th>
    <div class="list-restaurant">
      <label class="radio-restaurant">
        <% restaurant = array[1] %>
        <%= radio_button_tag(:restaurant, restaurant.id) %>
        <img  class= "individual-chosen-image" src="<%=restaurant.image_url%>" height="180" width="250"/>
      </label>
      </br>
      $<%= restaurant.price %>
      </br>
  <%= link_to restaurant_path(restaurant.id) do %>
  <p class="restaurant-name">
    <%= label_tag(:restaurant, restaurant.name) %>
  </p>
  <% end %>

      </br>
      </br>
    </div>
  </th>

<th>
    <div class= "list-event">
      <label class="radio-event">
        <% event = array[0] %>
        <%= radio_button_tag(:event, event.id) %>
        <img  class= "individual-chosen-image" src="<%=event.image_url%>" height="180" width="250"/>
      </label>
      </br>
        $<%= event.price %>
      </br>

      <%= link_to event_path(event.id) do %>
        <%= label_tag(:event, event.name) %>
      <% end %>
      </br>
      </br>
    </div>

  <% end %>
</th>


  </td>
  <p>
    Your total would be approximately $<%= @price_max * @quantity %> for <%= @quantity %> person(s).
  </p>
    <input type="submit" name="commit" value="Save" />
  <%= hidden_field_tag :date, params["date"] %>
<% end %>
</section>

app/views/date_plan/show.html.erb
<h2 class="planned-date">
  Here is your date plan for:
  <%= @date_plan.date.strftime('%A, %b %e %Y') %>
</h2>

<h4>
  What you have saved:
</h4>
Restaurant:
  <%= link_to restaurant_path(@date_plan.restaurant.id) do %>
    <%= @date_plan.restaurant.name %>
  <% end %>
</br>

Event:
  <%= link_to event_path(@date_plan.event.id) do %>
    <%= @date_plan.event.name %>
  <% end %>
<div class="delete-button-plan">
  <%= button_to "delete", show_date_plan_url(@date_plan), method: :delete, data: {confirm: "Are you sure you want to delete your plan?"}%>
</div>