config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :restaurants
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :restaurants
  root 'welcome#homepage'

  get '/welcome', to: 'welcome#homepage'
  get '/welcome/choice', to: 'welcome#select_choices'
  get '/welcome/trending', to: 'welcome#trending'
  get '/welcome/about', to: 'welcome#about'
  get '/date_plan', to: 'date_plan#plan'
  post '/date_plan', to: 'date_plan#create'
  get '/date_plan/:id', to: 'date_plan#show', as: 'show_date_plan'
  delete '/date_plan/:id', to: 'date_plan#destroy'
  get '/user', to: 'user#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :date_plans
  has_many :restaurants, through: :date_plans
  has_many :events, through: :date_plan
  validates :picture, :first_name, :last_name, presence: true

  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image

      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
 end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    load_user
    @date_plans = @user.date_plans
  end

  def destroy
    load_user
    @date_plan = @date_plans.find_by(:id)
    @user.date_plan.find_by(:id)
    redirect_to root
  end



  private

  def load_user
    @user = User.find_by(id: current_user.id)
  end


end

app/views/user/show.html.erb
<h1> Hi <%= @user.first_name %></h1>

<p>
   Here are the plans you have saved:
 </p>

<% @date_plans.each do |date_plan| %>
<div class="individual-date-plan">
  <p> Here is your plan for </p>
<%= link_to date_plan.date.strftime('%A, %b %e %Y'), show_date_plan_path(date_plan)  %>
  <%= date_plan.restaurant.name %>
  <img src="<%=date_plan.restaurant.image_url %>" height="200" width="200"/>
  <%= date_plan.event.name %>
  <img src="<%= date_plan.event.image_url %>" height="200" width="200"/>
  <br />

</div>
<% end %>