config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :restaurants
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :restaurants
  root 'welcome#homepage'

  get '/welcome', to: 'welcome#homepage'
  get '/welcome/choice', to: 'welcome#select_choices'
  get '/welcome/trending', to: 'welcome#trending'
  get '/welcome/about', to: 'welcome#about'
  get '/date_plan', to: 'date_plan#plan'
  post '/date_plan', to: 'date_plan#create'
  get '/date_plan/:id', to: 'date_plan#show', as: 'show_date_plan'
  delete '/date_plan/:id', to: 'date_plan#destroy'
  get '/user', to: 'user#show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#603cba">
    <meta name="theme-color" content="#CE696A">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Oinker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>


    <div class="login_logout">


      <div class='close'id="menuToggle">
        <div class='bar1'></div>
        <div class='bar2'></div>
        <div class='bar3'></div>
       </div>
       <span>&nbsp</span>
        <a href="/">
         <img class="logo" src="/assets/logo3c.png">
        </a>
     </div>



    <div id="wrapper">

   <!-- Sidebar -->
    <div id="sidebar-wrapper">
       <ul class="sidebar-nav">



           <li>
               <%=link_to('Home', root_path)%>
           </li>
           <li>
               <%=link_to('Trending', welcome_trending_path)%>
           </li>
           <li>
               <%=link_to('Make Plans', welcome_choice_path)%>
           </li>

           <%if !current_user %>
           <li>
             <%=link_to('Log in', new_user_session_path)%>
           </li>
           <li>
            <%=link_to('Sign up', new_user_registration_path)%>
           </li>

           <%end%>

           <li>
               <%=link_to('About Us', welcome_about_path)%>
           </li>

           <% if current_user %>
             <li>
              <%=image_tag(current_user.picture, class:'profile_image')%>
              <p><%=current_user.first_name%> <%=current_user.last_name%></p>
            </li>
            <li>
                <%=link_to('Logout', destroy_user_session_path, :method => :delete)%>
            </li>

           <%end%>

       </ul>
   </div>
   <!-- /#sidebar-wrapper -->

   <!-- Page Content -->
   <div id="page-content-wrapper">
       <div class="container-fluid">
    <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
    <% end %>


<main class='content'>
  <body>
    <%=yield%>
  </body>
</main>

  <footer id="footer">
      <p>Copyright Oinker Inc. |  <%=link_to('About Us', welcome_about_path)%></p>
  </footer>

</html>